import Env from '@ioc:Adonis/Core/Env'

export default Env.rules({
  HOST: Env.schema.string({ format: 'host' }),
  PORT: Env.schema.number(),
  APP_KEY: Env.schema.string(),
  APP_NAME: Env.schema.string(),
  NODE_ENV: Env.schema.enum(['development', 'production', 'testing'] as const),
  PG_HOST: Env.schema.string({ format: 'host' }),
  PG_PORT: Env.schema.number(),
  PG_USER: Env.schema.string(),
  PG_PASSWORD: Env.schema.string.optional(),
  PG_DB_NAME: Env.schema.string(),
  BULL_REDIS_HOST: Env.schema.string({ format: 'host' }),
  BULL_REDIS_PORT: Env.schema.number(),
  BULL_REDIS_PASSWORD: Env.schema.string.optional(),
  CACHE_VIEWS: Env.schema.boolean(),
  UNIMED_BASE_URL: Env.schema.string({ format: 'url' }),
  INTERMED_BASE_URL: Env.schema.string({ format: 'url' }),
  TOKEN_UNIMED: Env.schema.string.optional(),
  TOKEN_INTERMED: Env.schema.string.optional(),
  RESOLVE_USER: Env.schema.string(),
  RESOLVE_PASSWORD: Env.schema.string(),
  RESOLVE_ID: Env.schema.string(),
})
